// New Arrivals
import shirt1 from "./assets/images/shirt1.png";
import jeans1 from "./assets/images/jeans.png";
import checkered from "./assets/images/checkered-shirt.png";
import striped from "./assets/images/striped-shirt.png";

// Top Selling
import top1 from "./assets/images/top1.png";
import top2 from "./assets/images/top2.png";
import top3 from "./assets/images/top3.png";
import top4 from "./assets/images/top4.png";

export const newArrivals = [
  {
    id: 1,
    image: shirt1,
    title: "T-SHIRT WITH TAPE DETAILS",
    stars: 5,
    ratingText: "4.5/5",
    price: 120,
    oldPrice: null,
    discount: null,
  },
  {
    id: 2,
    image: jeans1,
    title: "SKINNY FIT JEANS",
    stars: 4,
    ratingText: "3.5/5",
    price: 240,
    oldPrice: null,
    discount: null,
  },
  {
    id: 3,
    image: checkered,
    title: "CHECKERED SHIRT",
    stars: 4,
    ratingText: "4.5/5",
    price: 180,
    oldPrice: 260,
    discount: "-20%",
  },
  {
    id: 4,
    image: striped,
    title: "SLEEVE STRIPED T-SHIRT",
    stars: 4,
    ratingText: "4.5/5",
    price: 130,
    oldPrice: 160,
    discount: "-30%",
  },
];

export const topSelling = [
  {
    id: 1,
    image: top1,
    title: "VERTICAL STRIPED SHIRT",
    stars: 5,
    ratingText: "5.0/5",
    price: 212,
    oldPrice: 232,
    discount: "-20%",
  },
  {
    id: 2,
    image: top2,
    title: "COURAGE GRAPHIC T-SHIRT",
    stars: 4,
    ratingText: "4.0/5",
    price: 145,
    oldPrice: null,
    discount: null,
  },
  {
    id: 3,
    image: top3,
    title: "LOOSE FIT BERMUDA SHORTS",
    stars: 3,
    ratingText: "3.0/5",
    price: 80,
    oldPrice: null,
    discount: null,
  },
  {
    id: 4,
    image: top4,
    title: "FADED SKINNY JEANS",
    stars: 4,
    ratingText: "4.5/5",
    price: 210,
    oldPrice: null,
    discount: null,
  },
];
export const casualProducts = [
  {
    id: 1,
    image: top2,
    title: "Gradient Graphic T-shirt",
    stars: 5,
    ratingText: "3.5/5",
    price: 145,
    oldPrice: null,
    discount: null,
  },
  {
    id: 2,
    image: shirt1,
    title: "Polo with Tipping Details",
    stars: 4,
    ratingText: "4.5/5",
    price: 180,
    oldPrice: null,
    discount: null,
  },
  {
    id: 3,
    image: striped,
    title: "Black Striped T-shirt",
    stars: 5,
    ratingText: "5.0/5",
    price: 120,
    oldPrice: 150,
    discount: "-30%",
  },
  {
    id: 4,
    image: jeans1,
    title: "Skinny Fit Jeans",
    stars: 4,
    ratingText: "3.5/5",
    price: 240,
    oldPrice: 260,
    discount: "-20%",
  },
  {
    id: 5,
    image: checkered,
    title: "Checkered Shirt",
    stars: 4,
    ratingText: "4.5/5",
    price: 180,
    oldPrice: null,
    discount: null,
  },
  {
    id: 6,
    image: striped,
    title: "Sleeve Striped T-shirt",
    stars: 4,
    ratingText: "4.5/5",
    price: 130,
    oldPrice: 160,
    discount: "-30%",
  },
  {
    id: 7,
    image: top1,
    title: "Vertical Striped Shirt",
    stars: 5,
    ratingText: "5.0/5",
    price: 212,
    oldPrice: 232,
    discount: "-20%",
  },
  {
    id: 8,
    image: top2,
    title: "Courage Graphic T-shirt",
    stars: 4,
    ratingText: "4.0/5",
    price: 145,
    oldPrice: null,
    discount: null,
  },
  {
    id: 9,
    image: top3,
    title: "Loose Fit Bermuda Shorts",
    stars: 3,
    ratingText: "3.0/5",
    price: 80,
    oldPrice: null,
    discount: null,
  },
];
